StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{63336833D030E5A6}" {
   Id "AFM_Core-Settings"
   Target_en_us "ArmaForces"
   ActorGender NONE
   Terminology NONE
   NonTranslatable 1
   Modified 1664319029
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{633338412D33224F}" {
   Id "AFM_Core-Settings_Radio"
   Target_en_us "Radio"
   Target_pl_pl "Radio"
   Modified 1664301385
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{63336828262A3010}" {
   Id "AFM_Core-Settings_Radio_Beep_1"
   Target_en_us "Beep"
   Target_pl_pl "Pisk"
   Modified 1664354288
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{63336828243BBF18}" {
   Id "AFM_Core-Settings_Radio_Beep_2"
   Target_en_us "Low Beep"
   Target_pl_pl "Niski Pisk"
   Modified 1664354286
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{633338413F2D1CB4}" {
   Id "AFM_Core-Settings_Radio_Beep_Ch1"
   Target_en_us "Ch. 1 sound"
   Target_pl_pl "Dźwięk kanału 1"
   Modified 1664354056
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{633338413D24B37A}" {
   Id "AFM_Core-Settings_Radio_Beep_Ch2"
   Target_en_us "Ch. 2 sound"
   Target_pl_pl "Dźwięk kanału 2"
   Modified 1664354059
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{633347584DC09AF9}" {
   Id "AFM_Core-Settings_Radio_Beep_Off"
   Target_en_us "Off"
   Target_pl_pl "Wyłączony"
   Modified 1664305029
   Author "veteran29"
   LastChanged "veteran29"
  }
 }
}