AFM_PapaBearConfig {
 m_aPapaBearEntryConfigs {
  AFM_PapaBearEntryConfig "{6628CE42241BF5A1}" {
   m_sMessageName "ARMAFORCES"
   m_sMessageText "PAPA BEAR TO ALL UNITS. ARMAFORCES ARE A BUNCH OF FAGS. OUT"
  }
  AFM_PapaBearEntryConfig "{6628CE42F4898EA0}" {
   m_sMessageName "MY_EVERON"
   m_sMessageText "SWEATY AMERICANS AND DEFAULT DANIELS. THIS IS WHAT MY EVERON IS ALL ABOUT. EVERY INCH OF THIS PLACE SEES ACTION. FROM MORTON TO SAINT PIERRE, YOU CAN SMELL THE RESOURCES"
  }
 }
}