StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{632902AEB3060991}" {
   Id "AR-Magazine_Hydra70_M257_Description"
   Modified 1663633683
   Author "nielu"
   LastChanged "nielu"
  }
  CustomStringTableItem "{632902AEB4BD53C3}" {
   Id "AR-Magazine_Hydra70_M257_Name"
   Target_en_us "70mm Illumination M257 Rocket"
   Modified 1663633750
   Author "nielu"
   LastChanged "nielu"
  }
  CustomStringTableItem "{632902ADA7CB7DD5}" {
   Id "AR-Magazine_S5_O1_Description"
   Modified 1663633693
   Author "nielu"
   LastChanged "nielu"
  }
  CustomStringTableItem "{632902ADA2969C10}" {
   Id "AR-Magazine_S5_O1_Name"
   Target_en_us "57mm Illumination S-5O1 Rocket"
   Modified 1663633697
   Author "nielu"
   LastChanged "nielu"
  }
 }
}