name: Build & Release

on:
  push: ~
  release:
    types: [published]

jobs:
  stable:
    if: github.ref_name == 'master'
    name: Stable
    runs-on: windows-2025
    steps:
      - name: Install DepotDownloader
        run: |
          winget install --disable-interactivity --accept-source-agreements --exact --id SteamRE.DepotDownloader --location C:\tools

      - name: Install Arma Reforger
        run: |
          C:\tools\DepotDownloader -dir c:\reforger -app 1874880 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: Install Arma Reforger Tools
        run: |
          C:\tools\DepotDownloader -dir C:\tools -app 1874910 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Mod

      - name: Workbench build
        run: >
          C:\tools\Workbench\ArmaReforgerWorkbenchSteamDiag.exe
          -enableWARP
          -exitAfterInit
          -noThrow
          -noSound
          -wbModule=ResourceManager
          -addonsDir "C:/reforger/addons/,${{ github.workspace }}/Mod/addons/"
          -addons "ArmaForces_Mods_Core"
          -profile "${{ github.workspace }}/profile"
          -packAddon
          -packAddonDir "${{ github.workspace }}/pack"

      - name: Archive profile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Stable profile
          path: profile
      - name: Archive pack
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Stable package
          path: pack

  experimental:
    name: Experimental
    runs-on: windows-2025
    steps:
      - name: Install DepotDownloader
        run: |
          winget install --disable-interactivity --accept-source-agreements --exact --id SteamRE.DepotDownloader --location C:\tools

      - name: Install Arma Reforger
        run: |
          C:\tools\DepotDownloader -dir c:\reforger -app 1890860 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: Install Arma Reforger Tools
        run: |
          C:\tools\DepotDownloader -dir C:\tools -app 1890880 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD}
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Steam Client Install
        run: |
          $url = 'https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe'
          Invoke-RestMethod -Uri $url -OutFile SteamSetup.exe
          .\SteamSetup.exe /S /D=C:\Steam
      - name: Steam Client Login
        run: |
          C:\Steam\steam.exe -silent -forceservice -login ${env:STEAM_USERNAME} ${env:STEAM_PASSWORD}
          sleep 10
        env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Mod

      - name: Experimental build
        run: >
          C:\tools\Workbench\ArmaReforgerWorkbenchSteamDiag.exe
          -enableWARP
          -exitAfterInit
          -noThrow
          -noSound
          -wbModule=ResourceManager
          -addonsDir "C:/reforger/addons/,${{ github.workspace }}\Mod/addons/"
          -addons "ArmaForces_Mods_Core"
          -profile "${{ github.workspace }}/output/profile"
          -packAddon
          -packAddonDir "${{ github.workspace }}/output/pack"

      - name: Test
        run: |
          ls ${{ github.workspace }}/output
          ls ${{ github.workspace }}/pack

      - name: Archive profile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Experimental profile
          path: output/profile
      - name: Archive pack
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Experimental Package
          path: output/pack

      - name: Archive steam logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Experimental Package
          path: C:\Steam\logs
