name: Build & Release

on:
  push: ~
  release:
    types: [published]

jobs:
  stable:
    if: github.ref_name == 'master'
    name: Stable
    runs-on: [self-hosted, Windows, steam]
    steps:
      - name: Install Arma Reforger
        run: |
          C:\tools\DepotDownloader -dir c:\tools\reforger -app 1874880 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD} -validate
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: Install Arma Reforger Tools
        run: |
          C:\tools\DepotDownloader -dir C:\tools\workbench -app 1874910 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD} -validate
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          path: Upstream
          persist-credentials: false

      - name: Steam Client Login
        run: |
          C:\Steam\steam.exe -silent -login ${env:STEAM_USERNAME} ${env:STEAM_PASSWORD}
          ${{ github.workspace }}\Upstream\tools\steam-check.exe
        env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}
        with:
          path: Source
      - name: Checkout pull request
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          path: Source
          ref: 'refs/pull/${{ github.event.number }}/merge'

      - name: Workbench build
        run: >
          C:\tools\workbench\Workbench\ArmaReforgerWorkbenchSteamDiag.exe
          -enableWARP
          -exitAfterInit
          -noThrow
          -noSound
          -wbModule=ResourceManager
          -addonsDir "C:/reforger/addons/,${{ github.workspace }}/Source/addons/"
          -addons "ArmaForces_Mods_Core"
          -profile "${{ github.workspace }}/profile"
          -packAddon
          -packAddonDir "${{ github.workspace }}/pack"

      - name: Archive profile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Stable profile
          path: profile
      - name: Archive pack
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Stable package
          path: pack

  experimental:
    name: Experimental
    runs-on: [self-hosted, Windows, steam]
    steps:
      - name: Install Arma Reforger
        run: |
          DepotDownloader -dir c:\tools\reforger-exp -app 1890860 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD} -validate
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      - name: Install Arma Reforger Tools
        run: |
          DepotDownloader -dir C:\tools\workbench-exp -app 1890880 -username ${env:STEAM_USERNAME} -password ${env:STEAM_PASSWORD} -validate
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          path: Upstream
          persist-credentials: false

      - name: Steam Client Login
        run: |
          C:\Steam\steam.exe -silent -login ${env:STEAM_USERNAME} ${env:STEAM_PASSWORD}
          ${{ github.workspace }}\Upstream\tools\steam-check.exe
        env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request_target' }}
        with:
          path: Source
      - name: Checkout pull request
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          path: Source
          ref: 'refs/pull/${{ github.event.number }}/merge'

      - name: Experimental build
        run: >
          C:\tools\workbench-exp\Workbench\ArmaReforgerWorkbenchSteamDiag.exe
          -enableWARP
          -exitAfterInit
          -noThrow
          -noSound
          -wbModule=ResourceManager
          -addonsDir "C:/reforger/addons/,${{ github.workspace }}\Source/addons/"
          -addons "ArmaForces_Mods_Core"
          -profile "${{ github.workspace }}/output/profile"
          -packAddon
          -packAddonDir "${{ github.workspace }}/output/pack"

      - name: Archive profile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Experimental profile
          path: output/profile
      - name: Archive pack
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Experimental Package
          path: output/pack
